#spring 配置信息
spring:
  jackson:
    #格式化后台返回时间
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      charset: UTF-8
    multipart:
      #临时目录，避免目录被删除，上传文件报错
      location: /app/files_root/temp